---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

