---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  root-password: root

# Using the kubectl create command:
# kubectl create secret generic mysql --from-literal=root-password=root

