apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pepsi-nginx
  name: pepsi-nginx
spec:
  containers:
  - image: nginx:1.11.5
    name: pepsi
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: config-volume
      configMap:
        name: pepsi-nginx

